name: Dandelion-dev CI

env:
  GH_TOKEN: ${{ github.token }} # Needed by gh cli
  # We default upload only to nightly release
  # as there's a limit on artifact storage space
  UPLOAD_TO_ARTIFACT: ${{ vars.UPLOAD_TO_ARTIFACT || false }}
  UPLOAD_TO_NIGHTLY: ${{ vars.UPLOAD_TO_NIGHTLY || true }}

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]

jobs:
  build_windows_x64_msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        build_kind: [dev, lib]
        build_type: [debug, release]
        include:
          - build_kind: dev
            cmake_root: .
          - build_kind: lib
            cmake_root: lib
          - should_upload: false
          - build_kind: lib
            should_upload: true
          - build_type: release
            should_upload: true
    env:
      ARTIFACT_NAME: dandelion-windows_msvc-x64-${{ matrix.build_kind }}-${{ matrix.build_type }}
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate VS build file
        run: |
          New-Item -ItemType "directory" build
          cmake -G "Visual Studio 17 2022" -S ${{ matrix.cmake_root }} -B build
      
      - name: Build Dandelion
        run: cmake --build build --config ${{ matrix.build_type }} --parallel $Env:NUMBER_OF_PROCESSORS
      
      - if: ${{ env.UPLOAD_TO_ARTIFACT && matrix.should_upload }}
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./build/${{ matrix.build_type }}/*

      - if: ${{ env.UPLOAD_TO_NIGHTLY && matrix.should_upload }}
        name: Upload Nightly
        run: |
          7z a -tzip -mx9 ${{ env.ARTIFACT_NAME }}.zip ./build/${{ matrix.build_type }}/*
          gh release upload nightly ${{ env.ARTIFACT_NAME }}.zip --clobber
