name: Remove old artifacts

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '5 day'
        skip-tags: true
        skip-recent: 2 # keep recent 2 artifacts